services:
  sms-service:
    image: jeffersonjeffersonpixel/sms-service:${VERSION}
    container_name: sms-service
    ports:
      - "${SMS_PORT}:${SERVER_PORT}"
    networks:
      - camdigikey
    environment:
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - ./.env-docker

  db:
    image: postgres
    container_name: sms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms-service
    ports:
      - "8001:5432"
    networks:
      - camdigikey


networks:
  camdigikey:
    driver: bridge