services:
  db:
    image: postgres
    container_name: sms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8001:5432"
    networks:
      - camdigikey

networks:
  camdigikey:
    driver: bridge